### PR TITLE
add showDelete config and optional delete button

### PR DESCRIPTION
**Pull request by bwinchester**
This adds an optional delete button, as well as a delete event that passes the deleted url in the event.data object argument

### CODE REVIEW

**Comment by themyth92** [comment]
Hi @bwinchester what is this deleted button used for ?

**Comment by bwinchester** [comment]
Hi @themyth92, yeah, so it adds a delete button to the bottom area of the image, just as rotate does, that fires a delete event for the users of the lightbox to optionally allow users to fire delete image events.

**Comment by themyth92** [comment]
Yeah but why user need this delete button ? I dont see the use case here.
I think this feature maybe more like selected image button make more sense. User can then do whatever they want with that (delete, send a request, ...) but then i think it is complicated (optional icon change, text change for that button to fit the use case ...).

**Comment by bwinchester** [comment]
Is there a selected image button?

**Comment by themyth92** [comment]
There is no selected button at the moment

**Comment by bwinchester** [comment]
Im closing this PR, I was just trying to follow the pattern of adding buttons in the row of buttons for a feature we needed, which seems useful. 

We ended up just writing our own shadow box component to suit our needs.

**Pull request closed without merging**
