### PR TITLE
add disable navigation config property

### PR DESCRIPTION
**Pull request by eyho**

### CODE REVIEW

**Comment by themyth92** [comment]
Hi, thanks for your PR. Could you tell me why this feature is needed ?

**Comment by eyho** [comment]
Hey, I was just browsing the open issues when I found this one: [28](https://github.com/themyth92/ngx-lightbox/issues/28)

Not sure if it'd be an overused feature though, up to you if you let it in or not.

**Comment by themyth92** [comment]
Hey @eyho , I think she wants to still allow navigation on the arrow but disable it when clicking on the image. Right now, the problem is because the click event is covered the whole image instead of the arrow.

**Comment by eyho** [comment]
@themyth92 Oh fine, I get it now. In this case, feel free to close this PR. :)

**Pull request closed without merging**
