### PR TITLE
Add a new option "enableTransition" to prevent infinite loader

### PR DESCRIPTION
**Pull request by ShamanisTe**
I using ngx-lightbox for display a gallery of picture in base64 which have nearly the same dimension. To prevent when "transitionEnd" is not fire, I adding a new property to directly display picture.

### CODE REVIEW

**Comment by themyth92** [comment]
Hi there. Thank you for your PR. Could you please fix the test as well as tell me why this option is necessary ?

**Comment by ShamanisTe** [comment]
Like i said, i have many gallery which need to display picture only in base64.
When i use arrow to view the next/previous picture, i often have an infinite loader cause by the event for "transitionEnd" is not fire so my picture is never displayed.

Following this case for picture with the same "newHeight"/"oldHeight" but different width.
When oldWidth = 354 and newWidth = 353, event is not fire
When oldWidth = 354 and newWidth = 352, event is fire

Maybe adding a property is not the correct solution. By adding a control to always have Two pixel between old/new working also.

Can you tell me your advice ?

**Comment by themyth92** [comment]
Hmm interesting. I saw some people report abt this problem but I have not replicated on my local yet. If possible could you give me 2 images that you have this problem with the current version so i can play with it. Really appreciate it.

**Comment by ShamanisTe** [comment]
Sorry, i can't give you this pictures (which cause the problem) because we can see some private information. Obsviously it's not arrive each time...
I try to produce the same problem on ur demo application by using Augury but all is OK :/

See the process of my app : 
In process the picture is taking by mobile phone -> send to server -> front app pull the data picture and read in FileReader to push it in ngx-lightbox

For information: macOS/chrome, angular v7.0.2

**Comment by themyth92** [comment]
Ok merged. Tks for your PR. I will bump the version from npm in a few hours as well as add the docs as well

**Pull request merged**
